import './globals.css'
import { Quicksand } from '@next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const generalSans = Quicksand({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-general',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} font-sans`}>{children}</body>
    </html>
  )
}
