/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/glbs/70/Tafeltje70.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js'
import { useLoader } from '@react-three/fiber'


export function Tafeltje70({
  props,
  onClick,
  imagedata,
  genredata,
  colorData,
}) {
  //First load in the mesh.
  const dracoLoader = new DRACOLoader()
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/')
  const gltf = useLoader(
    GLTFLoader,
    '/glbs/70/Tafeltje70-transformed.glb',
    (loader) => {
      loader.setDRACOLoader(dracoLoader)
    },
  )
  const { nodes, materials, animations } = gltf


  return (
    <group
      onClick={() => onClick('era_tafeltje70')}
      {...props}
      scale={20}
      rotation={[0, 1.5, 0]}
      position={[-30, -18, -23]}
      dispose={null}
    >
      <mesh geometry={nodes.OPM0032.geometry} material={colorData[3]} />
    </group>
  )
}

useGLTF.preload('/glbs/70/Tafeltje70-transformed.glb')
