/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/glbs/90s/stoeltje.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js'
import { useLoader } from '@react-three/fiber'

export function Stoeltje({ props, onCLick, imagedata, genredata, colorData }) {
  const dracoLoader = new DRACOLoader()
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/')
  const gltf = useLoader(
    GLTFLoader,
    '/glbs/90s/stoeltje-transformed.glb',
    (loader) => {
      loader.setDRACOLoader(dracoLoader)
    },
  )
  const { nodes, materials, animations } = gltf


  return (
    <group onClick={() => onClick('era_stoeltje')} {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.stoeltje_1.geometry} material={colorData[7]} />
        <mesh geometry={nodes.stoeltje_2.geometry} material={colorData[2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/glbs/90s/stoeltje-transformed.glb')
