/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/glbs/90s/Tafeltje90.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js'
import { useLoader } from '@react-three/fiber'

export function Tafeltje90({
  props,
  onClick,
  imagedata,
  genredata,
  colorData,
}) {
  const dracoLoader = new DRACOLoader()
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/')
  const gltf = useLoader(
    GLTFLoader,
    '/glbs/90s/Tafeltje90-transformed.glb',
    (loader) => {
      loader.setDRACOLoader(dracoLoader)
    },
  )
  const { nodes, materials, animations } = gltf

  return (
    <group onClick={() => onClick('era_tafeltje90')} {...props} dispose={null}>
      <group position={[-31, -7, -20]} rotation={[Math.PI / 2, 0, 0]} scale={4}>
        <mesh geometry={nodes.Mesh.geometry} material={colorData[6]} />
        <mesh geometry={nodes.Mesh_1.geometry} material={colorData[3]} />
      </group>
    </group>
  )
}

useGLTF.preload('/glbs/90s/Tafeltje90-transformed.glb')
