/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/glbs/10s/tafeltje.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js'
import { TextureLoader } from 'three'
import { useLoader } from '@react-three/fiber'
import { MeshStandardMaterial } from 'three'

export function Tafeltje({props,imagedata,genredata}) {
  //const { nodes, materials } = useGLTF('/tafeltje-transformed.glb')

   //First load in the mesh.
  const dracoLoader = new DRACOLoader()
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/')
  const gltf = useLoader(
    GLTFLoader,
    '/glbs/10s/tafeltje-transformed.glb',
    (loader) => {
      loader.setDRACOLoader(dracoLoader)
    },
  )
  const { nodes, materials, animations } = gltf
  
  const texture = useLoader(TextureLoader, imagedata[3].image)
  const brownmaterial = new MeshStandardMaterial({ color: 0x7f675b })

  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.79, -3.64]} rotation={[Math.PI / 2, 0, 0]} scale={0.31}>
        <mesh geometry={nodes.tafeltje_1.geometry} material={materials['tafeltje:aiStandardSurface1SG']} />
        <mesh geometry={nodes.tafeltje_2.geometry} material={materials['tafeltje:aiStandardSurface1SG']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glbs/10s/tafeltje-transformed.glb')
