/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 finalwork/public/80s90s.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
import { TextureLoader } from 'three';
import * as THREE from "three";
import { MeshBasicMaterial } from 'three';


export function Model80s({ props, imageData, genreData, dominantColor }) {

  console.log("loading model... with data:")
 // console.log(imageData)
 // console.log(genreData)
  //console.log(dominantColor)
  

  const dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/');

  const gltf = useLoader(GLTFLoader, '/80s90s-transformed.glb', (loader) => {
    loader.setDRACOLoader(dracoLoader);
  });

  const { nodes, materials } = gltf;

  //let image=imageData[0].image;
  const texture = useLoader(TextureLoader, imageData[3].image);


  const color = new THREE.Color(1, 60, 80); // RGB values for red

  const material = new MeshBasicMaterial({ color });
  

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mat.geometry} material={materials['Material.020']} position={[0.01, 0.03, -0.07]} rotation={[Math.PI / 2, 0, 0]} scale={[0.06, 0.06, 0.01]} />
      <group position={[-0.16, 0.11, -0.25]} rotation={[Math.PI / 2, 0, 0.95]} scale={[0.09, 0.07, 0.17]}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials.lambert2} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.wooden} />
      </group>
      <group position={[-0.12, 0.03, 0.07]} rotation={[-Math.PI / 2, 0, 1.58]} scale={0.01}>
        <mesh geometry={nodes.Mesh002.geometry} material={materials.Pillow_Blanket} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials['material.001']} />
      </group>
      <mesh geometry={nodes.House002.geometry} material={material}  position={[0, 0.13, 0.2]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.02, 0.4, 0.27]} />
      <group name='vinyls'>
          <mesh geometry={nodes.pCube65.geometry} material={materials.poster3surfae} position={[0.09, 0.21, 0.18]} rotation={[1.57, Math.PI * 5, -1.6]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={texture} />
            </mesh>
          <mesh geometry={nodes.pCube66.geometry} material={materials.poster3surfae} position={[0.12, 0.15, 0.18]} rotation={[1.57, Math.PI * 5, -1.6]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={texture} />
          </mesh>
          <mesh geometry={nodes.pCube67.geometry} material={materials.poster3surfae} position={[0.08, 0.15, 0.18]} rotation={[1.57, Math.PI * 5, -1.6]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={texture} />
          </mesh>
          <mesh geometry={nodes.pCube68.geometry} material={materials.poster3surfae} position={[0.13, 0.21, 0.18]} rotation={[1.57, Math.PI * 5, -1.6]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={texture} />
          </mesh>
          <mesh geometry={nodes.pCube69.geometry} material={materials.poster3surfae} position={[-0.05, 0.15, 0.18]} rotation={[1.57, Math.PI * 5, -1.6]} scale={[0.001, 0.03, 0.05]}>
                    <meshStandardMaterial map={texture} />
            </mesh>
          <mesh geometry={nodes.pCube70.geometry} material={materials.poster3surfae} position={[0.02, 0.2, 0.18]} rotation={[1.57, -0.15, -1.6]} scale={[0.001, 0.03, 0.05]}>
                    <meshStandardMaterial map={texture} />
          </mesh>
        </group>
        <group name='posters'>
          <mesh geometry={nodes.pCube71.geometry} material={materials.poster3surfae} position={[0.06, 0.08, 0.04]} rotation={[1.53, 0.1, 2]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={useLoader(TextureLoader, imageData[0].image)} />
          </mesh>
          <mesh geometry={nodes.pCube72.geometry} material={materials.poster3surfae} position={[0.06, 0.08, 0.05]} rotation={[1.55, 0.2, 1.93]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={useLoader(TextureLoader, imageData[1].image)} />
                </mesh>
          <mesh geometry={nodes.pCube73.geometry} material={materials.poster3surfae} position={[0.07, 0.08, 0.03]} rotation={[1.57, 0.01, 0.87]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={useLoader(TextureLoader, imageData[2].image)} />
                </mesh>
          <mesh geometry={nodes.pCube74.geometry} material={materials.poster3surfae} position={[0, 0.09, 0.15]} rotation={[1.51, 0.05, 0.11]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={useLoader(TextureLoader, imageData[3].image)} />
                </mesh>
          <mesh geometry={nodes.pCube75.geometry} material={materials.poster3surfae} position={[0.02, 0.09, 0.16]} rotation={[1.66, 0.14, 0.47]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={useLoader(TextureLoader, imageData[4].image)} />
                </mesh>
          <mesh geometry={nodes.pCube76.geometry} material={materials.poster3surfae} position={[0.01, 0.08, 0.15]} rotation={[1.53, 0.05, 0.63]} scale={[0.001, 0.03, 0.05]}>
            <meshStandardMaterial map={texture} />
                </mesh>
            </group>
      <group position={[-0.17, 0.19, -0.01]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.04, 0.06]}>
        <mesh geometry={nodes.Mesh016.geometry} material={materials.poster3surfae} />
        <mesh geometry={nodes.Mesh016_1.geometry} material={materials.poster3surfae} />
      </group>
      <mesh geometry={nodes.cabinet1_tex_cupboard_0.geometry} material={materials.tex_cupboard} position={[-0.04, 0.02, 0.01]} rotation={[-1.8, -1.56, -1.8]} scale={0} />
      <mesh geometry={nodes.CouchpCylinder2.geometry} material={materials.poster3surfae} position={[0.13, -0.05, 0.11]} rotation={[Math.PI / 2, 0, -2.06]} scale={0.02} />
      <group position={[-0.03, 0.08, -0.16]} rotation={[1.87, -0.93, -2.75]} scale={0.02}>
        <mesh geometry={nodes.Mesh019.geometry} material={materials['drumpad:Material_002']} />
        <mesh geometry={nodes.Mesh019_1.geometry} material={materials['drumpad:Material_004']} />
        <mesh geometry={nodes.Mesh019_2.geometry} material={materials['drumpad:Material_006']} />
        <mesh geometry={nodes.Mesh019_3.geometry} material={materials['drumpad:Material_008']} />
        <mesh geometry={nodes.Mesh019_4.geometry} material={materials['drumpad:Material_010']} />
        <mesh geometry={nodes.Mesh019_5.geometry} material={materials['drumpad:Material_012']} />
        <mesh geometry={nodes.Mesh019_6.geometry} material={materials['drumpad:Material_012']} />
      </group>
      <group position={[-0.09, 0.02, -0.07]} rotation={[Math.PI / 2, 0, 2.87]} scale={0.01}>
        <mesh geometry={nodes.Mesh020.geometry} material={materials['OBJlamp:defaultMaterialSG1']} />
        <mesh geometry={nodes.Mesh020_1.geometry} material={materials['OBJlamp:defaultMaterialSG1']} />
        <mesh geometry={nodes.Mesh020_2.geometry} material={materials['OBJlamp:defaultMaterial.005SG1']} />
        <mesh geometry={nodes.Mesh020_3.geometry} material={materials.poster3surfae} />
        <mesh geometry={nodes.Mesh020_4.geometry} material={materials['OBJlamp:defaultMaterial.005SG1']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh021.geometry} material={materials.poster3surfae} />
        <mesh geometry={nodes.Mesh021_1.geometry} material={materials.poster3surfae} />
      </group>
      <mesh geometry={nodes.pCube78.geometry} material={materials.poster3surfae} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/80s90s-transformed.glb')
