/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect  } from "react";
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useGLTF, useAnimations } from "@react-three/drei";


export function Computer(props) {
   //const { nodes, materials } = useLoader(GLTFLoader, '/suzanne.gltf')
    const gltf = useGLTF('/computerV2_anim.glb')
    const { nodes, materials, animations } = useGLTF("/computerV2_anim.glb");
    console.log("computer ey!")
    //console.log(nodes)
    //console.log(materials)
    //console.log(animations)
    const { actions, names } = useAnimations(animations)
    //console.log(actions)
     useEffect(() => {
    console.log(names[0])
    console.log(actions)
   //actions.TopAction.play();
    
  });

    //position={[5,0,0]} rotation={[Math.PI / 8, 0.2, 0]}
    
  return (
      <group >
      {nodes && <primitive object={nodes.Scene} />}
      {materials && Array.isArray(materials) && materials.map((material, index) => (
        <primitive key={index} object={material} />
      ))}
    </group>
  );
}

//useGLTF.preload("/suzanne.gltf");
