/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 finalwork/public/posterrr.gltf --transform
Author: Cas.de.Bruijn (https://sketchfab.com/Cas.de.Bruijn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trashposter-ea3670dfcfd74250a7e6bd73c313b34b
Title: trashposter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ props,imageData}) {
  const { nodes, materials } = useGLTF('/posterrr-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.poster3} position={[0.05, 0.2, 0.18]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/posterrr-transformed.glb')
