/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 finalwork/public/v1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
import { TextureLoader } from 'three';

export function Model({ props,imageData}) {
  const dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/');

  const gltf = useLoader(GLTFLoader, '/v1-transformed.glb', (loader) => {
    loader.setDRACOLoader(dracoLoader);
  });

  const { nodes, materials } = gltf;

  //let image=imageData[0].image;
  const texture = useLoader(TextureLoader, imageData[3].image);


  return (
    <group {...props} dispose={null}>
      <group position={[-0.14, 0.12, 0.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.06, 0.11, 0.17]}>
        <group position={[-0.4, -1.07, 0.02]} rotation={[0, 0, 0.79]}>
          <mesh geometry={nodes.Mesh004.geometry} material={materials.lambert2}>
             <meshStandardMaterial map={texture} />
          </mesh>
          <mesh geometry={nodes.Mesh004_1.geometry} material={materials.wooden}>
            <meshStandardMaterial map={texture} />
          </mesh>
        </group>
      </group>
      <group position={[-0.04, 0.07, 0.15]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.recordplayer.geometry} material={materials.lambert28} position={[-74.77, -5.04, 0]} />
        </group>
      </group>
      <group position={[0.11, 0.03, 0.07]} rotation={[-Math.PI / 2, 0, 1.58]} scale={0.01}>
        <group position={[-0.02, -2, -0.35]}>
          <mesh geometry={nodes.Mesh006.geometry} material={materials.Pillow_Blanket} />
          <mesh geometry={nodes.Mesh006_1.geometry} material={materials['material.001']} />
        </group>
      </group>
      <group position={[0.04, 0.07, 0.16]} rotation={[Math.PI / 2, 0, -2.48]} scale={0.07}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group rotation={[0, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Banker_Lamp_1_LP_M_Lamp_Bank_0.geometry} material={materials.M_Lamp_Bank} position={[-0.03, 0.08, 0]} />
          </group>
        </group>
      </group>
      <group position={[-0.13, 0.03, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial005.geometry} material={materials['1001']} />
          <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['1001']} />
          <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['1001']} />
          <mesh geometry={nodes.defaultMaterial004.geometry} material={materials['1001']} />
          <mesh geometry={nodes.defaultMaterial003.geometry} material={materials['1001']} />
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['1001']} />
        </group>
      </group>
      <group position={[-0.12, 0.2, 0.07]} rotation={[-Math.PI / 2, 0, -0.66]} scale={0}>
        <group scale={100}>
          <mesh geometry={nodes.Box_Box_Material_0.geometry} material={materials.Box_Material} position={[0, 0, -0.03]} />
        </group>
      </group>
      <mesh geometry={nodes.mat.geometry} material={materials['Material.020']} position={[0.01, 0.03, -0.07]} rotation={[Math.PI / 2, 0, 0]} scale={[0.06, 0.06, 0.01]} />
      <group position={[-0.01, 0.05, 0.16]} rotation={[Math.PI / 2, 0, 0]} scale={[0.14, 0.04, 0.04]}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials.kastje_mainsurface} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.kastje_randjesLade} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials.kastje_laden} />
        <mesh geometry={nodes.Mesh001_3.geometry} material={materials.lade_handvat} />
      </group>
      <mesh geometry={nodes.table.geometry} material={materials.lambert2} position={[-0.1, 0.08, -0.07]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.04]} />
      <group position={[-0.07, 0.07, -0.14]} rotation={[1.3, 0.23, 2.33]} scale={[0.01, 0.01, 0.02]}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials.lambert2} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.Zitje} />
      </group>
      <mesh geometry={nodes.House002.geometry} material={materials.standardSurface3} position={[0, 0.13, 0.2]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.02, 0.4, 0.27]} />
      <mesh geometry={nodes.Plaat1.geometry} material={materials.Vinyl1Surface} position={[0.01, 0.07, 0.15]} rotation={[Math.PI / 2, 0, -2.82]} scale={[-0.03, -0.03, 0]} />
      <mesh geometry={nodes.Plaat2.geometry} material={materials.Vinyl1Surface} position={[0, 0.07, 0.16]} rotation={[Math.PI / 2, -0.05, 3.04]} scale={[-0.03, -0.03, 0]} />
      <mesh geometry={nodes.Plaat3.geometry} material={materials.Vinyl1Surface} position={[-0.01, 0.07, 0.15]} rotation={[Math.PI / 2, -0.03, 3.06]} scale={[-0.03, -0.03, 0]} />
      <mesh geometry={nodes.Plaat4.geometry} material={materials.Vinyl1Surface} position={[-0.02, 0.07, 0.15]} rotation={[Math.PI / 2, 0.02, -1.55]} scale={[-0.03, -0.03, 0]} />
      <mesh geometry={nodes.Plaat5.geometry} material={materials.Vinyl5Surface} position={[-0.07, 0.07, 0.15]} rotation={[Math.PI / 2, 0, 3.11]} scale={[-0.03, -0.03, 0]} />
      <mesh geometry={nodes.pCube65.geometry} material={materials.standardSurface3} position={[0.09, 0.21, 0.18]} rotation={[Math.PI / 2, 0, -1.6]} scale={[0, 0.04, 0.05]} />
      <mesh geometry={nodes.pCube66.geometry} material={materials.standardSurface3} position={[0.12, 0.15, 0.18]} rotation={[1.57, -0.01, -1.6]} scale={[0, 0.04, 0.05]} />
      <mesh geometry={nodes.pCube67.geometry} material={materials.standardSurface3} position={[0.08, 0.15, 0.18]} rotation={[1.57, 0.08, -1.6]} scale={[0, 0.04, 0.05]} />
      <mesh geometry={nodes.pCube68.geometry} material={materials.standardSurface3} position={[0.13, 0.21, 0.18]} rotation={[1.57, -0.01, -1.6]} scale={[0, 0.03, 0.05]} />
      <mesh geometry={nodes.pCube69.geometry} material={materials.standardSurface3} position={[-0.05, 0.15, 0.18]} rotation={[1.57, 0, -1.6]} scale={[0, 0.06, 0.09]} />
      <mesh geometry={nodes.pCube70.geometry} material={materials.standardSurface3} position={[0.02, 0.2, 0.18]} rotation={[-0.49, -1.54, 2.65]} scale={[0, 0.04, 0.05]} />
      <mesh geometry={nodes.pCube71.geometry} material={materials.standardSurface3} position={[-0.11, 0.11, -0.16]} rotation={[Math.PI / 2, 0, -1.99]} scale={[0.02, 0.03, 0]} />
      <mesh geometry={nodes.pCube72.geometry} material={materials.standardSurface3} position={[-0.11, 0.11, -0.14]} rotation={[1.62, 0.02, -1.95]} scale={[0.02, 0.03, 0]} />
      <mesh geometry={nodes.pCube73.geometry} material={materials.standardSurface3} position={[-0.13, 0.11, -0.16]} rotation={[1.57, 0.09, -0.92]} scale={[0.02, 0.03, 0]} />
      <mesh geometry={nodes.pCube74.geometry} material={materials.standardSurface3} position={[-0.11, 0.11, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.02, 0]} />
      <mesh geometry={nodes.pCube75.geometry} material={materials.standardSurface3} position={[-0.09, 0.11, -0.06]} rotation={[Math.PI / 2, 0, 0.09]} scale={[0.01, 0.02, 0]} />
      <mesh geometry={nodes.pCube76.geometry} material={materials.standardSurface3} position={[-0.1, 0.11, -0.06]} rotation={[Math.PI / 2, 0, 0.56]} scale={[0.01, 0.02, 0]} />
      <group position={[-0.17, 0.19, -0.14]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.04, 0.06]}>
        <mesh geometry={nodes.Mesh033.geometry} material={materials.standardSurface3} />
        <mesh geometry={nodes.Mesh033_1.geometry} material={materials.standardSurface3} />
      </group>
    </group>
  )
}

useGLTF.preload('/v1-transformed.glb')
