/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/glbs/10s/boekjes.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js'
import { TextureLoader } from 'three'
import { useLoader } from '@react-three/fiber'
import { MeshStandardMaterial } from 'three'

export function Boekjes({props,imagedata,genredata}) {
  //const { nodes, materials } = useGLTF('/boekjes-transformed.glb')

  //First load in the mesh.
  const dracoLoader = new DRACOLoader()
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/')
  const gltf = useLoader(
    GLTFLoader,
    '/glbs/10s/boekjes-transformed.glb',
    (loader) => {
      loader.setDRACOLoader(dracoLoader)
    },
  )
  const { nodes, materials, animations } = gltf
  
  const texture = useLoader(TextureLoader, imagedata[3].url)
  const brownmaterial = new MeshStandardMaterial({ color: 0x7f675b })

  return (
    <group {...props} dispose={null}>
      <group position={[-55, -23.5, -50]} rotation={[Math.PI / 2, 0.1, 0]} scale={3}>
        <mesh geometry={nodes.Magazines_1.geometry} position={[0, 0, 1.7]} rotation={[0, 0.1, 0]} material={materials.aiStandardSurface9SG}>
           <meshStandardMaterial
            map={useLoader(TextureLoader, imagedata[0].url)}
          />
          </mesh>
        <mesh geometry={nodes.Magazines_2.geometry} position={[1.6, -2, -1.4]} rotation={[0.1, 0, 0]} material={materials.aiStandardSurface9SG}>
           <meshStandardMaterial
            map={useLoader(TextureLoader, imagedata[0].url)}
          />
          </mesh>
        <mesh geometry={nodes.Magazines_3.geometry} position={[0.2, 2.2, -1.4]} rotation={[0, -0.1, 0]} material={materials.aiStandardSurface9SG}>
           <meshStandardMaterial
            map={useLoader(TextureLoader, imagedata[0].url)}
          />
          </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/glbs/10s/boekjes-transformed.glb')
