/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/glbs/10s/dvd.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js'
import { TextureLoader } from 'three'
import { useLoader } from '@react-three/fiber'
import { MeshStandardMaterial } from 'three'

export function Dvd({props,imagedata,genredata}) {
  //const { nodes, materials } = useGLTF('/dvd-transformed.glb')

  //First load in the mesh.
  const dracoLoader = new DRACOLoader()
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/')
  const gltf = useLoader(
    GLTFLoader,
    '/glbs/10s/dvd-transformed.glb',
    (loader) => {
      loader.setDRACOLoader(dracoLoader)
    },
  )
  const { nodes, materials, animations } = gltf
  
  const texture = useLoader(TextureLoader, imagedata[3].url)
  const brownmaterial = new MeshStandardMaterial({ color: 0x7f675b })
  return (
    <group {...props} dispose={null}>
      <group scale={2.5} position={[-4, -10, -47]} rotation={[1.5, 0, 1.2]}>
        <mesh geometry={nodes.DVDs_1.geometry} material={materials.aiStandardSurface11SG}>
          <meshStandardMaterial
            map={useLoader(TextureLoader, imagedata[0].url)}
          />
          </mesh>
        <mesh geometry={nodes.DVDs_2.geometry} material={materials.aiStandardSurface11SG}>
          <meshStandardMaterial
            map={useLoader(TextureLoader, imagedata[0].url)}
          />
          </mesh>
        <mesh geometry={nodes.DVDs_3.geometry} material={materials.aiStandardSurface11SG}>
          <meshStandardMaterial
            map={useLoader(TextureLoader, imagedata[0].url)}
          />
          </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/glbs/10s/dvd-transformed.glb')
