/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/glbs/10s/tvs.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js'
import { TextureLoader } from 'three'
import { useLoader } from '@react-three/fiber'
import { MeshStandardMaterial } from 'three'

export function Tvs({ props, onClick, imagedata, genredata, colorData }) {
  //First load in the mesh.
  const dracoLoader = new DRACOLoader()
  dracoLoader.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/')
  const gltf = useLoader(
    GLTFLoader,
    '/glbs/10s/tvs-transformed.glb',
    (loader) => {
      loader.setDRACOLoader(dracoLoader)
    },
  )
  const { nodes, materials, animations } = gltf

  return (
    <group
      onClick={() => onClick('era_tvs')}
      scale={2.5}
      position={[-19, -15, -50]}
      rotation={[0, -1.5, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.TV.geometry}
        material={colorData[3]}
        position={[0, 0, -6.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.8}
      />
    </group>
  )
}

useGLTF.preload('/glbs/10s/tvs-transformed.glb')
